### ISSUE TITLE
[UI] Adding new robot to the list highlights all the robots in the list

### ISSUE THREAD

**Issue by xalpol12** [xalpol12/kuka-ar-all#23]
When a robot from the list is chosen (indicated by the highlighted entry) and then the next robot is added to the list, it results in all the robots from the list being highlighted. Clicking on one of the entries from the list fixes this bug until the next robots is added.

[link to a video](https://drive.google.com/file/d/1eSJAjqOaJDZv-fWOh-ONT29HDmB7ZNQF/view?usp=sharing)

**Comment by CoyotWilly** [comment]
Ok that's sth new as I been fixing this bug like 4 times and it keeps coming back. Funny how unity play with me, I been testing and fixing all observable robots related problems about Wednesday so it should be fine, unless notification system some how had impact on in (even though it shouldn't)
Unity 🤡

**Comment by xalpol12** [comment]
But Unity is not responsible for version control, especially when behavior is contained in .cs files. 
Maybe you already fixed it, I noticed this bug on my branch feature/ui-ar-without-popup, which is a version without 2.09.2023 changes that introduced popup.

**Comment by CoyotWilly** [comment]
If it's a old pop-up sys ( mid screen placed with 2 buttons ) than it can be but if it's a new one ( push notification like),  then it's a new system , so if I will have the same problem on my local branch I will fix if not then more info will be required to target it and hopefully fix it 😀

**Comment by CoyotWilly** [comment]
Solved in 40b635f459778bd8ad81120bc33e5aeb7d6861bc, review and feedback would be great

**Comment by xalpol12** [comment]
Looks great, for what I've tested, the issue has been resolved 👍
