### ISSUE TITLE
[UI & Java] Possibility of adding the same robot more than once

### ISSUE THREAD

**Issue by xalpol12** [xalpol12/kuka-ar-all#24]
There is a possibility to persist two robots with the same ip address to a database, which creates a situation where it's impossible to delete them from database, backend service throws an error:
```
jakarta.persistence.NonUniqueResultException: query did not return a unique result: 2
```

* UI action should call update (not post), when the robot with given ip already exists. 
* Besides that, I think the database should have a unique constraint (or some kind of business logic) to prevent from adding the same ip twice.

**Comment by xalpol12** [comment]
It's partially completed, now we have to implement behavior in Unity app so that when the POST "/robots" fails then POST "/update" will be called. Any ideas how we can do it @CoyotWilly ?

**Comment by CoyotWilly** [comment]
Actually I do, let's wrap a POST response and if 400 will be returned then we will call UPDATE, and let's hope that it'll work.

**Comment by CoyotWilly** [comment]
Actually I do, let's wrap a POST response and if 400 will be returned then we will call UPDATE, and let's hope that it'll work.

**Comment by xalpol12** [comment]
yes, I will contact you tomorrow
