### ISSUE TITLE
[UI on Android] Enlarge slide up and down area of the main list

### ISSUE THREAD

**Issue by xalpol12** [xalpol12/kuka-ar-all#25]
Is it possible to enlarge the area of sliding list containing saved robots? Right now it's really difficult to grab the list and slide it up, I struggle so hard :(

**Comment by CoyotWilly** [comment]
Yeah sure it's 5min work fix, i only need to know how big slider trgger area would you like to have ?? Currently it's 330x72 [px]

**Comment by xalpol12** [comment]
I would certainly welcome a wider area, heigh is ok, you could add a few pixels, but I think main issue on my phone is the width.

**Comment by CoyotWilly** [comment]
Since it's very personal i will leave you a path were it can be adjusted:
`Menu->Canvas->SafeArea->BottomNavController-> Slider` and then **Left** and **Right** params in RectTrandform, feel free to commit those changes

**Comment by xalpol12** [comment]
Sure, will do, thanks

**Comment by xalpol12** [comment]
changed to LEFT = RIGHT = 350 in [4d73af7](https://github.com/xalpol12/kuka-ar-all/commit/4d73af79f4714e5e9436dd7c66606ec84b89f23c)
