### ISSUE TITLE
[Android & UI] UiController class Start() method does not invoke 

### ISSUE THREAD

**Issue by xalpol12** [xalpol12/kuka-ar-all#27]
While testing on Android I encountered a problem, when the app starts the `UiController`'s `Start()` method should invoke `MutableImageRecognizer` and `AnchorManager` Coroutine functions that fetch data from server to AR logic. Right now it's not happening on Android. I tested the same functionality in Unity Editor and it does not seem to be an issue there. 

The idea here is to have a point of entry where some fetch functions could be invoked on application start. Now we have two cases:
* The application is started for the first time on the device - server ip configuration window shows up and all fetch functions are invoked on save button click
* The application has a cached server ip address and does not display configuration window - then we have to invoke the fetch functions in some place that is executed once, on app start. `UiController`'s `Start()` method seemed to be a good place for it. 

**Since it does not work now, we have to manually go to the server config window and click `Save` button to invoke fetching data for AR logic to work**

**Comment by CoyotWilly** [comment]
Ok, checked everything works as it was before. Log cat is not showing any issue related errors. Merge request and you ready to go.

**Comment by xalpol12** [comment]
In a few minutes, I rebased my fix branch onto main and now building app to check if every fix works as intended.

**Comment by xalpol12** [comment]
Ok, checked and I only have to add invocation in case user clicked "Report debug", then the new scene is loaded and when "back arrow is clicked" the data is not loaded.
