### ISSUE TITLE
[Suggestion] Check out Microsoft's "Performance recommendations for Unity" and implement changes

### ISSUE THREAD

**Issue by xalpol12** [xalpol12/kuka-ar-all#31]
[Performance recommendations for mixed reality apps by Microsoft](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/performance-recommendations-for-unity?tabs=openxr) provides some good practices and recommendations to follow in order to optimize the app for Android. We could check it out and cross-check if our app implements these recommendations.

**Comment by CoyotWilly** [comment]
## Throw away
No need for futher improvement at this moment (14/11/2023). Moving all work force into official documentation part.
