### ISSUE TITLE
[UI] Robot list duplication 

### ISSUE THREAD

**Issue by xalpol12** [xalpol12/kuka-ar-all#35]
@CoyotWilly is aware of this issue, it also happened on sprint review. For some reason the entries from main robot's list are sometimes being duplicated - the list is doubled in size.

**Comment by CoyotWilly** [comment]
Let me know if you are able to reproduce this bug. I was trying to do so today (09/17/2023) but without any success. 😢

**Comment by CoyotWilly** [comment]
## Issue update
Ready to be tested. Solved in fd55de27c5150f6fd6225dbf03027e3d90b45495. Pull request will show up at Friday as I'm currently fixing some details and improving display feel&look.
