### ISSUE TITLE
[UI] Truncate float values of jogs to one decimal point

### ISSUE THREAD

**Issue by xalpol12** [xalpol12/kuka-ar-all#49]
Right now "JOINTS" section of UI displays an immediate value that is received from server, which causes the joint values to display outside the border of the window, making it kind of illegible. 
**Proposition:** truncate displaying value to one decimal point 
**Example:** Convert received value j1: 40.125921 -> j1: 40.1

**Comment by xalpol12** [comment]
Yeah sure, I'm doing code review right now, but I will wait then for the fix

**Comment by CoyotWilly** [comment]
Solved in bf14b41bea97da8d27bb47271e20adae1a941cc2, passing for review and tests. 🚀 🐛

**Comment by xalpol12** [comment]
🫡

**Comment by xalpol12** [comment]
:saluting_face:
