### ISSUE TITLE
[UI] Connection status does not refresh instantly

### ISSUE THREAD

**Issue by xalpol12** [xalpol12/kuka-ar-all#53]
When user selects a robot, the connection status switches to `Connecting`. Then, if an image associated with this robot is scanned and recognised successfully, app sends a request to receive data updates from websocket. If package from websocket contains ip that is equal to the ip of a selected robot, then connection status is changed to `Connected`. But in order to update this value in UI, user must refresh the bottom nav by dragging it up and down, only then the UI shows the correct status. 

Is there a method to update UI connection status instantly?

**Comment by CoyotWilly** [comment]
Ofc there are 2 way to do so:
- call a method `ConnectionStatusCheckHandler` from `ObservableRobotsBehavior.cs`
- get and call method `OverrideStatusLabel` from `LabelOverride.cs` with is a singleton and takes a string with status

I would recommend to use the second approach as it was created for problems like this, and to avoid assembly ref problems 😄
