### ISSUE TITLE
Add new robots list 

### ISSUE THREAD

**Issue by CoyotWilly** [xalpol12/kuka-ar-all#61]
## Issue 🐛 
1. Currently list entires display relies on array max size (one of following: `IpAddress`,`ConfiguredRobot`, `RobotsCategory`). When user will pull many items it couses infinty scroll to appear.
2. IP address should be sorted [UX improve request]
3. All items received from server should be displayed, currently not all of them are

## Acceptance criteria 🏁  
1. List displays all items received from server
2. IP address are sorted
3. Previous functionalities are still available

## Question
**@xalpol12 Is this behavior fine ??**
![image](https://github.com/xalpol12/kuka-ar-all/assets/114695131/dd07e3ee-4e37-44e1-9869-7f8a417a5373)

Detailed message received from Unity when trying to parse list of stickers with not valid name [not IP]
![image](https://github.com/xalpol12/kuka-ar-all/assets/114695131/70626d37-9791-4fb5-a300-c7ad1f0afbec)

**Or do we want anythink else, more fancy/less visible (error handled under the hood)/ remove totally ??**

**Comment by CoyotWilly** [comment]
## Work progress 🧾 
1. Solved in bf66c6cab2a52ff878eebb38ab9126977fb9eafb
2. Solved in bf66c6cab2a52ff878eebb38ab9126977fb9eafb
3. Solved in bf66c6cab2a52ff878eebb38ab9126977fb9eafb

## What's for tommorow ⏭️ 
1. Code clean up 🧹 
2. More detailed tests 🧪 
3. Phone tests 📱

**Comment by xalpol12** [comment]
@CoyotWilly 
> ## Question
> **@xalpol12 Is this behavior fine ??** ![image](https://user-images.githubusercontent.com/114695131/281164492-dd07e3ee-4e37-44e1-9869-7f8a417a5373.png)

Yeah it looks good, we can use the notification system to notify user about the problem with an image - but it would be good to provide more detailed message in that notification, something along the lines: "Detected image with name: {{ incorrectIpAddress }}, which is not a correct ip address. This image will not be added." Or something similar - to indicate which image caused problems - if it's possible of course

**Comment by CoyotWilly** [comment]
Yeah it's actually not that hard, I'm gonna make it today on the lecture.
